# Laboratorinis 12

## 1 uzd

Parašykite programą, kuri išsprendžia lygčių sistemą ir suapvalintą atsakymą išveda stulpeliu.

Pirmoje eilutėje pateikti du skaičiai n ir m:  
n - lygčių skaičius,  
m - nežinomųjų skaičius.  
Toliau n eilučių, kiekvienoje eilutėje m+1 skaičius. Pirmi m skaičių - tai lygties nežinomųjų koeficientai, paskutinis skaičius - lygties rezultatas.

n ir m nebūtinai lygūs

In [56]:
import numpy as np

n, m = map(int, input().split())
arr_list = []
arr_res_list = []
for i in range(n):
    *rowA, rowB = list(map(int, input().split()))
    arr_list.append(rowA)
    arr_res_list.append(rowB)
    
arr_list = np.array(arr_list)
arr_res_list = np.array(arr_res_list)

res = np.linalg.lstsq(arr_list, arr_res_list)[0] # solve

if res.any():
    for r in res:
        print(np.round(r, decimals = 1))
else:
    print("Sprendinys neegzistuoja.")

 2 3
 1 2 3 0
 9 8 7 0


Sprendinys neegzistuoja.


C:\Users\GEDIMI~1\AppData\Local\Temp/ipykernel_12376/2545135694.py:14: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  res = np.linalg.lstsq(arr_list, arr_res_list)[0] # solve


## 2 uzd

Parašykite programą, kuri išsprendžia matricinę lygtį A*x = B

n - matricos dimensija
Kvadratinės matricos A ir B

Matrica x

In [43]:
import numpy as np

n = int(input())

c_arr = []
r_arr = []
for i in range(n):
    c_arr.append(list(map(int, input().split())))
    
for i in range(n):
    r_arr.append(list(map(int, input().split())))
    
c_arr = np.array(c_arr)
r_arr = np.array(r_arr)

res = np.linalg.solve(c_arr, r_arr)
print(res)

 3
 1 0 3
 1 -4 1
 -2 3 -5
 10 -7 -10
 -14 -3 18
 -4 12 1


[[-2. -1.  2.]
 [ 4. -0. -5.]
 [ 4. -2. -4.]]


## 3 uzd

Parašykite programą, kuri išsprendžia matricinę lygtį x*A = B.

n - matricos dimensija  
Kvadratinės matricos A ir B

Matrica x

In [56]:
import numpy as np

n = int(input())

c_arr = []
r_arr = []
for i in range(n):
    c_arr.append(list(map(int, input().split())))
    
for i in range(n):
    r_arr.append(list(map(int, input().split())))
    
c_arr = np.array(c_arr)
r_arr = np.array(r_arr)

res = np.matmul(r_arr, np.linalg.inv(c_arr))
print(np.round(res, decimals=1))

 3
 5 2 -4
 -5 -5 -5
 0 -1 -2
 0 3 6
 25 5 -30
 -5 -3 -1


[[ 0.  0. -3.]
 [ 5. -0.  5.]
 [-0.  1. -2.]]


## 4 ud

Iš failo duom.txt nuskaitykite ir išveskite masyvą. Pakeiskite masyvo reikšmes inf reikšmėmis 100, o reikšmes nan reikšmėmis -10. Rezultatą įrašykite į failą rez.txt.

In [88]:
import numpy as np

d = np.loadtxt("duom.txt")
print(d)
d[np.isinf(d)] = 100
d[np.isnan(d)] = -10

# def f(x):
#     if np.isinf(x):
#         return 100
#     elif np.isnan(x):
#         return -10
#     return x
    
# fv = np.vectorize(f)

# d = fv(d)
print(d)

np.savetxt("rez.txt", d, fmt = "%i")

[[ 1. nan  3.]
 [ 4.  5.  6.]
 [ 7.  8. inf]]
[[  1. -10.   3.]
 [  4.   5.   6.]
 [  7.   8. 100.]]


In [ ]:
# np.set_printoptions(formatter={'float': '{: 0.1f}'.format}) # / np.set_printoptions(precision=1)

In [119]:
np.set_printoptions(suppress=None, precision = None)

## 5 uzd

Duota matrica a(n x n) ir vienmatis masyvas b(1 x n). Parašykite programą, kuri pakelia kiekvienos eilutės elementą atitinkamu laipsniu (iš masyvo b).

In [17]:
import numpy as np
np.set_printoptions(suppress=True)

n = int(input())

arr = []
for i in range(n):
    arr.append(list(map(float, input().split())))
    
arr = np.array(arr)
arr2 = np.array(list(map(float, input().split()))).reshape(1, n)

arr = np.power(arr, arr2)
print(arr)

 4 
 1 2 3 4
 5 6 7 8
 9 10 11 12
 13 14 15 16
 2 2 3 3


[[   1.    4.   27.   64.]
 [  25.   36.  343.  512.]
 [  81.  100. 1331. 1728.]
 [ 169.  196. 3375. 4096.]]


## 6 uzd

Sukurkite universalią dviejų parametrų funkciją. Pirmas parametras (a) – dvimatis masyvas, antras (b) – vienmatis arba dvimatis masyvas. Funkcija turi grąžinti dvimatį masyvą. Jeigu pirmo ir antro masyvų elemento reikšmės lygios, grąžina -1. Jeigu pirmo masyvo elemento reikšmė didesnė – grąžinama reikšmių dalybos liekana (aJeigu pirmo masyvo elemento reikšmė mažesnė – grąžinama reikšmių sandauga (a*b).

n - a masyvo eilučių skaičius masyvas a m - b masyvo eilučių skaičius masyvas b

a ir b masyvo stulpelių skaičius visada lygus n

In [1]:
import numpy as np
np.set_printoptions(suppress=True)

n = int(input())
a = []
for i in range(n):
    a.append(list(map(float, input().split())))
a = np.array(a)
    
m = int(input())
b = []
for i in range(m):
    b.append(list(map(float, input().split())))
b = np.array(b)

def f(x, y):
    if x == y:
        return -1.
    elif x > y:
        return x%y
    elif x < y:
        return x*y
    return x

vf = np.vectorize(f)

a = vf(a, b)
print(a)

 3
 1 2 3
 4 5 6
 7 8 9
 1
 1 2 10


[[-1. -1. 30.]
 [ 0.  1. 60.]
 [ 0.  0. 90.]]


## 7 uzd

Duotas dvimatis masyvas a. Ciklo for pagalba modifikuokite masyvą, apskaičiuodami kiekvieno elemento kubą.

In [13]:
import numpy as np
np.set_printoptions(suppress=True)

n, m = map(int, input().split())

a = np.array([list(map(float, input().split())) for i in range(n)])

for e in np.nditer(a, op_flags = ['readwrite']):
    e[...] = np.power(e, 3)

print(a)

 3 4
 10 11 12 13
 14 15 16 17
 18 19 20 21


[[1000. 1331. 1728. 2197.]
 [2744. 3375. 4096. 4913.]
 [5832. 6859. 8000. 9261.]]


## 8 uzd

Duotas masyvas a(4x4) ir masyvas b = (1x4). Funkcijos where() pagalba atrinkite masyvo a reikšmes (a[i][j] < 5) ir pakelkite jas atitinkamu laipsniu (iš masyvo b). Kitas reikšmes padauginkite iš 5.

In [15]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(float, input().split())) for i in range(4)]) 
b = np.array(list(map(float, input().split())))

a = np.where(a < 5, np.power(a, b), a*5)

print(a)

 0 6 2 4
 9 1 4 3
 1 3 4 8
 3 1 8 8
 2 3 4 5


[[   0.   30.   16. 1024.]
 [  45.    1.  256.  243.]
 [   1.   27.  256.   40.]
 [   9.    1.   40.   40.]]


## 9 uzd

Duotas masyvas a(4x4). Išspausdinkite:

eilučių didžiausias reikšmes ir didžiausių reikšmių indeksus;  
stulpelių mažiausias reikšmes ir mažiausių reikšmių indeksus;  
visų elementų sumą;  
visų elementų vidurkį.

In [30]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(float, input().split())) for i in range(4)]) 

print(*np.max(a, axis = 1))
print(*np.argmax(a, axis = 1))
print(*np.min(a, axis = 0))
print(*np.argmin(a, axis = 0))
print(np.sum(a))
print(np.mean(a))

 31 45 48 13
 44 17 24 14
 40 27 25 49
 32 33 68 71


48.0 44.0 49.0 71.0
2 0 3 3
31.0 17.0 24.0 13.0
0 1 1 0
581.0
36.3125


## 10 uzd

Duota kvadratinė matrica(4x4). Išspausdinkite:

stulpelių kaupiamąją elementų sandaugą  
visų elementų kaupiamąją sandaugą  
stulpelių kaimyninių elementų skirtumus.

In [41]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(float, input().split())) for i in range(4)])

print(np.cumsum(a, axis = 0)) # sandauga? (cumprod)
print()
print(np.cumsum(a))
print()
print(np.diff(a, axis = 0))

[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]
 [28 32 36 40]]

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136]

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


## 11 uzd

Duoti du masyvai a ir b. Išspausdinkite:

unikalias reikšmes, esančias abiejuose masyvuose;  
unikalias antro masyvo reikšmes, kurių nėra pirmame masyve;  
unikalias reikšmes, kurios yra tik viename (ne abiejuose) masyvuose.

In [6]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))

print(list(np.intersect1d(a, b)))
print(list(np.setdiff1d(b, a)))
print(list(np.setxor1d(a,b)))

 1 2 3 4 5 6 7 8 9 10 11
 2 4 6 8 10 12


[2, 4, 6, 8, 10]
[12]
[1, 3, 5, 7, 9, 11, 12]


## 12 uzd

Duotas (nXn) masyvas. Nustatykite, ar masyve yra bent vienas nulinis elementas. Išveskite atitinkamą pranešimą.

In [22]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
n = np.array([list(map(int, input().split())) for i in range(n)])

if 0 in n: # arba su np.all()
    print("yra 0")
else:
    print("nera 0")

 2
 1 2
 3 4


nera 0
