# Laboratorinis 13

## 1 uzd

Duotas masyvas a.
Iš masyvo a pašalinkite inf, -inf ir nan reikšmes.

In [2]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(eval(input()))
# a = np.array([10, 20, np.NINF, np.nan, np.inf])
a = np.delete(a, np.where(np.isinf(a)))
a = np.delete(a, np.where(np.isnan(a)))

print(a)


 10, 20, np.NINF, np.nan, np.inf


[10. 20.]


## 2 uzd

Duotas masyvas (4x4). Išveskite antrą pagal dydį vertę.

In [6]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(int, input().split())) for i in range(4)])

a = np.unique(a)
a = np.sort(a)

print(a[-2])

7


## 3 uzd

Duotas masyvas (4x4).
Išveskite pirmo elemento, kurio vertė >3 kordinates

In [21]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(int, input().split())) for i in range(4)])
# a = np.array([[2, 4, 1, 3],
#               [4, 3, 3, 2],
#               [4, 0, 2, 0],
#               [0, 4, 4, 2]])

print(*np.unravel_index(np.argmax(a > 3), shape = a.shape))


0 1


## 4 uzd

Duotas masyvas a (3x5).
Surūšiuokite eilutes taip, kad trečio stulpelio elementai būtų išdėstyti didėjimo tvarka.

In [35]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array([list(map(float, input().split())) for i in range(3)])
# a = np.array([[5, 0, 1, 3, 2],
#             [-3, 2, 9, 4, 8],
#             [-1, 6, 3, 1, 3]])

a = a[a[:, 2].argsort()]

print(a)

[[ 5  0  1  3  2]
 [-1  6  3  1  3]
 [-3  2  9  4  8]]


## 5 uzd

Parašykite programą, kuri surūšiuoti vardų (first_names) ir pavardžių (last_names) poras (pirmiausia pagal pavardę, po to pagal vardą).
Išveskite surūšiuotas poras.

In [46]:
import numpy as np
np.set_printoptions(suppress = True)

first_names = np.array(eval(input()))
last_names = np.array(eval(input()))
arr_type = [('last_name', 'U10'), ('first_name', 'U10')]

arr = np.ones(len(first_names), dtype = arr_type)

arr['first_name'] = first_names
arr['last_name'] = last_names

arr.sort(order = ['last_name', 'first_name'])
for p in arr:
    print(*p)


 ("Margery","Betsey","Shelley","Lanell","Genesis","Andy")
 ("Woolum","Battle","Plotner","Brien","Stahl","Battle")


Battle Andy
Battle Betsey
Brien Lanell
Plotner Shelley
Stahl Genesis
Woolum Margery


## 6 uzd

Duotas masyvas a (nxn).
Surūšiuokite paskutinę masyvo eilutę.

In [50]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
a = np.array([list(map(float, input().split())) for i in range(n)])

a[-1].sort() # a[-1, :/...]

print(a)

 3
 -1.0111 -1.4711 0.8705
 -0.3318 -0.3436 2.1714
 0.1773 0.7424 0.8548


[[-1.0111 -1.4711  0.8705]
 [-0.3318 -0.3436  2.1714]
 [ 0.1773  0.7424  0.8548]]


## 7 uzd

Duotas masyvas a.  
Išveskite k mažiausių reikšmių. Masyvo nerūšiuokite!.

Note  
Privalote pasinaudoti numpy bibliotekos funkcionalumu. Jei rūšiuosite masyvą gausite neteisingą atsakymą.

In [55]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(float, input().split())))
k = int(input())

a.partition(k)
print(a[:k])

 1 7 8 2 0.1 3 15 2.5 10 1.3 0.2 5
 5


[0.1 0.2 1.  1.3 2. ]


## 8 uzd

Duotas masyvas a (6x6) intervale.  
Išveskite mažiausią elemento reikšmę.  
Išveskite pirmo mažiausio elemento indeksų rinkinį (tuple).  
Išveskite visų mažiausių elementų indeksų masyvą.

In [76]:
import numpy as np
np.set_printoptions(suppress = True)

# a = np.array([list(map(int, input().split())) for i in range(6)])

a = np.array([[3, 8, 6, 2, 6, 8],
            [1, 7, 4, 7, 2, 5],
            [1, 8, 8, 6, 7, 9],
            [3, 2, 1, 7, 4, 5],
            [6, 6, 5, 4, 5, 7],
            [6, 9, 7, 4, 3, 1]])

min_val = a.min()
print(min_val)
print(np.unravel_index(a.argmin(), shape = a.shape))
temp = np.where(a==min_val)
temp = np.stack([*temp], axis = 1)
# temp = np.concatenate([temp[0].reshape(-1, 1), temp[1].reshape(-1, 1)], axis = 1)
print(temp)

1
(1, 0)
[[1 0]
 [2 0]
 [3 2]
 [5 5]]
