# Laboratorinis 12

## 1 uzd

Parašykite programą, kuri išsprendžia lygčių sistemą ir suapvalintą atsakymą išveda stulpeliu.

Pirmoje eilutėje pateikti du skaičiai n ir m:  
n - lygčių skaičius,  
m - nežinomųjų skaičius.  
Toliau n eilučių, kiekvienoje eilutėje m+1 skaičius. Pirmi m skaičių - tai lygties nežinomųjų koeficientai, paskutinis skaičius - lygties rezultatas.

n ir m nebūtinai lygūs

In [36]:
import numpy as np

n, m = map(int, input().split())
arr_list = []
arr_res_list = []
for i in range(n):
    tmp = list(map(int, input().split()))
    arr_list.append(tmp[:-1])
    arr_res_list.append(tmp[-1])
    
arr_list = np.array(arr_list)
arr_res_list = np.array(arr_res_list)

res = np.linalg.solve(arr_list, arr_res_list)

for r in res:
    print(np.round(r, decimals = 1))

# nu tipo galima prideti kad jei ats vien 0 tai tada ir 0 ats bus. Arba jei vien vienetai tiek lygciu sis. tiek atsakymuos tada gaunasi vien 1 but yeah

 4 4
 1 2 -1 1 0
 3 3 -5 2 0
 -3 1 4 -5 0
 1 3 -2 1 0


0.0
0.0
0.0
0.0


## 2 uzd

Parašykite programą, kuri išsprendžia matricinę lygtį A*x = B

n - matricos dimensija
Kvadratinės matricos A ir B

Matrica x

In [43]:
import numpy as np

n = int(input())

c_arr = []
r_arr = []
for i in range(n):
    c_arr.append(list(map(int, input().split())))
    
for i in range(n):
    r_arr.append(list(map(int, input().split())))
    
c_arr = np.array(c_arr)
r_arr = np.array(r_arr)

res = np.linalg.solve(c_arr, r_arr)
print(res)

 3
 1 0 3
 1 -4 1
 -2 3 -5
 10 -7 -10
 -14 -3 18
 -4 12 1


[[-2. -1.  2.]
 [ 4. -0. -5.]
 [ 4. -2. -4.]]


## 3 uzd

Parašykite programą, kuri išsprendžia matricinę lygtį x*A = B.

n - matricos dimensija  
Kvadratinės matricos A ir B

Matrica x

In [56]:
import numpy as np

n = int(input())

c_arr = []
r_arr = []
for i in range(n):
    c_arr.append(list(map(int, input().split())))
    
for i in range(n):
    r_arr.append(list(map(int, input().split())))
    
c_arr = np.array(c_arr)
r_arr = np.array(r_arr)

res = np.matmul(r_arr, np.linalg.inv(c_arr))
print(np.round(res, decimals=1))

 3
 5 2 -4
 -5 -5 -5
 0 -1 -2
 0 3 6
 25 5 -30
 -5 -3 -1


[[ 0.  0. -3.]
 [ 5. -0.  5.]
 [-0.  1. -2.]]


## 4 ud

Iš failo duom.txt nuskaitykite ir išveskite masyvą. Pakeiskite masyvo reikšmes inf reikšmėmis 100, o reikšmes nan reikšmėmis -10. Rezultatą įrašykite į failą rez.txt.

In [68]:
import numpy as np

d = np.loadtxt("duom.txt")
print(d)
d[np.isinf(d)] = 100
d[np.isnan(d)] = -10

# def f(x):
#     if np.isinf(x):
#         return 100
#     elif np.isnan(x):
#         return -10
#     return x
    
# fv = np.vectorize(f)

# d = fv(d)

print(d)

[[ 1. nan  3.]
 [ 4.  5.  6.]
 [ 7.  8. inf]]
0.0
[[  1. -10.   3.]
 [  4.   5.   6.]
 [  7.   8. 100.]]
