# Laboratorinis 14

## 1 uzd  
Parašykite NumPy programą, kad sukurtumėte dvimatį masyvą (nxn) su 1 kraštuose ir 0 viduje.

In [2]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
arr = np.ones((n,n))
arr[1:-1,1:-1] = 0
print(arr)

 4


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## 2 uzd

Duotas masyvas a.
Išveskite vienetų ir nulių skaičius.

In [13]:
import numpy as np
np.set_printoptions(suppress = True)

arr = np.array(list(map(int, input().split())))
bc = np.bincount(arr)
print(f"vienetu - {bc[1] if len(bc) > 1 else 0}")
print(f"nuliu - {bc[0]}")
# print(f"vienetu - {np.sum((arr == 1))}")
# print(f"nuliu - {np.sum((arr == 0))}")


 0 0 0 0


vienetu - 0
nuliu - 4


## 3 uzd

Parašykite programą, kuri sukuria dvimatį masyvą, kurio įstrižainė yra duotas masyvas, o likę elementai lygūs 0.

In [14]:
import numpy as np
np.set_printoptions(suppress = True)

a = list(map(float, input().split()))

print(np.diag(a))

 1 2 3 4


[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


## 4 uzd

Duotas masyvas. Pakeiskite reikšmes > 5 reikšme 5

In [18]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(int, input().split())))

a = np.where(a > 5, 5, a)

print(a)

 1 3 5 7 9


[1 3 5 5 5]


## 5 uzd

Duotas skaičius n.  
Sukurkite nulių masyvą a(nxn) ir parašykite programą, kuri pakeičia masyvo reikšmes taip, kaip parodyta

In [27]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
a = np.zeros((n, n))

a[:] = np.arange(n) 

# a = np.arange(n, dtype = np.float16)
# a = np.tile(a, [n, 1])

print(a)

 4


[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


## 6 uzd

Duotas masyvas a.  
Parašykite programą, kuri apskaičiuoja ir išveda elementų, kurie dalijasi iš 5 ir nesidalija iš 2 sandaugą.

In [36]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(int, input().split())))

print(np.prod(a[(a % 5 == 0) & (a % 2 != 0)]))

 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20


75


## 7 uzd

Duotas vienmatis masyvas a. Išveskite elementų, kurių reikšmė > 25, skaičių.

In [48]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(int, input().split())))

print(len(np.where(a>25)[0]))

 43 2 12 28 40 37 28 23 25 46


6


## 8 uzd

Duotas masyvas a  
Viena komanda pašalinkite iš jo elementus su indeksais duotais masyve b

In [52]:
import numpy as np
np.set_printoptions(suppress = True)

a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))

a = np.delete(a, b)

print(a)

 100 101 102 103 104 105 106 107 108 109 110
 2 3 4 5


[100 101 106 107 108 109 110]


## 9 uzd

Duotas dvimatis masyvas (nxn).  
Pašalinkite stulpelius, kuriose yra nan reikšmė.

In [107]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
# a = np.array([[eval(input().replace(' ', ','))] for i in range(n)], dtype = np.float16)
a = np.array([input().split() for i in range(n)])
a = np.where(a == 'np.nan', np.nan, a)
a = np.array(a, dtype = np.float16)

# a = np.delete(a, np.isnan(a).any(axis=0), axis = 1)

d = np.where(np.isnan(a))
if len(d[0]) > 0:
    a = np.delete(a, d[1], axis = 1)

print(a)

# print(a[:, ~np.isnan(a).any(axis=0)])

 4
 np.nan 2 3 4
 5 6 7 8
 9 10 11 np.nan
 13 14 15 16


[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


## 10 uzd

Sukurkite universalią funkciją (ufunc), kuri turi du parametrus a ir b.  
Kur  
a – dvimatis masyvas (nxn);  
b – arba skaičius (1), arba vienmatis masyvas (2), arba dvimatis masyvas (3)  
Funkcija grąžina masyvą, kur kiekvienas elementas apskaičiuojamas kaip paelementinio skirtumo modulis |a - b|.  

Input  
n - a masyvo dimensijos  
a  
skaicius 1, 2 arba 3, kuris nusako kokio tipo bus b  
b

In [117]:
import numpy as np
np.set_printoptions(suppress = True)

def ufunc(a, b):
    return np.abs(a - b)

n = int(input())
a = np.array([list(map(float, input().split())) for i in range(n)])
m = int(input())
if m == 1:
    b = int(input())
elif m == 2:
    b = np.array(list(map(float, input().split())))
elif m == 3:
    b = np.array([list(map(float, input().split())) for i in range(n)])
    
uf = np.vectorize(ufunc)
    
print(uf(a, b))


 4
 -1 -2 -3 -4
 0 0 0 5
 1 1 1 2
 2 3 4 2
 3
 1 2 3 4
 5 6 7 8
 9 10 11 12
 13 14 15 16


[[ 2.  4.  6.  8.]
 [ 5.  6.  7.  3.]
 [ 8.  9. 10. 10.]
 [11. 11. 11. 14.]]


## 11 uzd

Sukurkite masyvą a(nxn), kuriame pagrindinėje įstrižainėje yra trejetai (3), pirmoje įstrižainėje virš pagrindinės – vienetai (1), visi kiti – nuliai (0)

In [122]:
import numpy as np
np.set_printoptions(suppress = True)

n = int(input())
a = np.eye(n) * 3
b = np.eye(n, k = 1)
a = a + b

print(a)


 4


[[3. 1. 0. 0.]
 [0. 3. 1. 0.]
 [0. 0. 3. 1.]
 [0. 0. 0. 3.]]
