In [1]:
class Egzaminas:
    stat_kint = 'statinis kintamasis'
    
    def __init__(self, paz):
        self.paz = paz
    
    @classmethod
    def cmethod(cls, a):
        cls.ckint = a
    
    @staticmethod
    def stmethod():
        print("hello from static method")
    
    def mult_paz(self, mult):
        return self.paz * mult
    
    def __str__(self):
        return f"Overloaded str: paz - {self.paz}, stat kint - {Egzaminas.stat_kint}"
        
    def numat_param(self, a = 10):
        return self.paz / a
    
    def kint_ilg_param(self, *n):
        return self.paz + sum(n)
    
    def vard_param(self, **n):
        return (self.paz + n['paz']) / n['dal']
    
a = Egzaminas(5)
print(Egzaminas.stat_kint)
print(a.paz)
a.cmethod(11)
print(a.ckint)
print(Egzaminas.ckint)
a.stmethod()
Egzaminas.stmethod()
print(a.mult_paz(3))
print(a.numat_param())
print(a.kint_ilg_param(1,2,3))
print(a.vard_param(paz = 10, dal = 2))
print(a)

print('--------------------')

class Testas(Egzaminas):
    def __init__(self, paz, test_num):
        super().__init__(paz)
        self.test_num = test_num
        
class Uzd(Egzaminas):
    def __init__(self, paz, uzd_num):
        super().__init__(paz)
        self.uzd_num = uzd_num
        
b = Testas(10, 1)
print(b.paz)
print(b.test_num)
print(b.numat_param())
c = Uzd(9, 2)
print(c.paz)
print(c.uzd_num)
print(c)

print('---------------------')

l = [1,2,3,4] # list - sarasas
t = (1,2,3,4) # tuple - rinkinys
d = dict.fromkeys(l, 0) # dict - zodynas
s = {1,2,3,4} # set - aibe

print(l, t, d, s, sep = '\n')

print('---------------------')

l = [a*2 for a in l]
print(l)

print('---')

inp = eval(input())
print(inp)

print('---')

inp = input().split(',')
print(inp)

print('---')

d = {'a': 100, 'b': 70, 'c': 250, 'd': 5, 'e': 25}
d = list(d.items())
print(d)
d.sort(key = lambda x: -x[1])
print(d)

print('---')

with open("duom2.txt", 'w') as f:
    f.write("Hello")
    
print('---------------------')

import numpy as np

print(np.arange(9).reshape(3,3))
print(np.ones([3,3]))
print(np.zeros([2,2]))
fful = np.full([2,2], 9)
print(fful)
print(np.random.randint(0, 10))
print(np.tile(fful, [3,1]))

statinis kintamasis
5
11
11
hello from static method
hello from static method
15
0.5
11
7.5
Overloaded str: paz - 5, stat kint - statinis kintamasis
--------------------
10
1
1.0
9
2
Overloaded str: paz - 9, stat kint - statinis kintamasis
---------------------
[1, 2, 3, 4]
(1, 2, 3, 4)
{1: 0, 2: 0, 3: 0, 4: 0}
{1, 2, 3, 4}
---------------------
[2, 4, 6, 8]
---


 1,2,3


(1, 2, 3)
---


 1,2,3


['1', '2', '3']
---
[('a', 100), ('b', 70), ('c', 250), ('d', 5), ('e', 25)]
[('c', 250), ('a', 100), ('b', 70), ('e', 25), ('d', 5)]
---
---------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[9 9]
 [9 9]]
7
[[9 9]
 [9 9]
 [9 9]
 [9 9]
 [9 9]
 [9 9]]
